SELECT Y.YELP_ID, Y.FIRST_NAME, Y.LAST_NAME FROM 
YELP_USER Y
WHERE
Y.BIRTHPLACE LIKE '%CA%' AND Y.YELP_ID NOT IN
(
SELECT U.YELP_ID FROM USER_CHECKEDIN U  
WHERE U.CHECKEDIN_BIZ IN 
(SELECT B.BUSINESS_ID FROM
BUSINESS B
WHERE B.ADDRESS LIKE '%CA%'));
