SELECT B.BUSINESS_ID FROM BUSINESS B 
WHERE B.DAYS_OPERATION NOT LIKE '%SUN%' AND B.AMBIENT LIKE '%Touristy%' AND B.STATE LIKE '%CA' 
AND B.BUSINESS_ID IN 
(SELECT R.BUSINESS_ID FROM REVIEWS R WHERE R.AUTHOR IN
(SELECT Y.YELP_ID FROM YELP_USER Y 
WHERE Y.BIRTHPLACE NOT LIKE '%CA%'
));